# coding: utf-8

from convert_functions3 import *
from populate_columns3 import (
    populate_wind_chill_english,
    populate_wind_chill_metric
)
from model_settings4_GOMv2 import (
    primary_RGA_list,
    component_RGA_list,
    all_RGAs
)

#WARNING - it's possible to get a mismatch between models if the include here and in project_specifics don't match

#Locations
#42001:		"lat":25.897,  "lon":-89.668,


#9042       "lat":28.5,     "lon":-90.75,
#8787       "lat":28.25,    "lon":-95.5,
#8544       "lat":27.875,   "lon":-84.0,
#7800       "lat":27.125,   "lon":-89.625,
#7712       "lat":27.0,     "lon":-85.75,
#7519       "lat":26.875,   "lon":-94.75,


#Next time - use smart_units in here.

output_root = "GOM_Output"
data_root = "data/GOM/"

wind_chill_function = populate_wind_chill_metric

NDBC_A_years = range(2005,2007) #[2005,2006]
NDBC_B_years = range(2007,2017)

inputs = {
    "clean": {#Provides settings for cleaning data.  Values over max are replaced, values under min become "null"
        "extremes": {#Goes through input data and cleans out unreasonable values, as set here.
            'wind': {'maximum': velocity(300,'mph'), 'minimum': 0},
            'gust': {'maximum': velocity(300,'mph'), 'minimum': 0},
            'wave': {'maximum': wave_height(150,'ft'), 'minimum': 0},
            'temp': {'maximum': temperature(100,'c'), 'minimum': temperature(-100,'c')},
            'period': {'maximum': period(2,'min'), 'minimum': period(0.1,'second')},
            'vis': {'maximum': smart_units('10 nmi'), 'minimum': 0},#Some older data includes very large visibility estimates (at least 100 km) but we're cutting these down to 16 km ~ 10 mi
            'ceil': {'maximum': smart_units('10 nmi'), 'minimum': 0}, #ceiling is in km
            'dir': {'maximum': 10000, 'minimum': 0},#Not limiting this, because other code handles >=360 values better.
            'cover': {'maximum': 1.0, 'minimum': 0.0} #Proportion (at least in WS)
        }
    },
    "years": range(2005,2017),
    "stations": {
        "42001_1": {
            "file_names": ["42001/42001h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":25.897,   "lon":-89.668,
            "time_offset": 0, #Offset from the time in the input file and UTC/UTM/GMT
            "UTM_offset":0, #Offset from internal and output time to UTC/UTM/GMT
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42001_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42001/42001h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":25.897,   "lon":-89.668,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42040_1": {
            "file_names": ["42040/42040h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":29.203,   "lon":-88.203,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42040_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42040/42040h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":29.203,   "lon":-88.203,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42039_1": {
            "file_names": ["42039/42039h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":28.739,   "lon":-86.006,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42039_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42039/42039h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":28.739,   "lon":-86.006,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42003_1": {
            "file_names": ["42003/42003h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":26.007,   "lon":-85.648,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42003_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42003/42003h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":26.007,   "lon":-85.648,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42002_1": {
            "file_names": ["42002/42002h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":26.091,   "lon":-93.758,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42002_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42002/42002h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":26.091,   "lon":-93.758,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42036_1": {
            "file_names": ["42036/42036h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":28.5,   "lon":-84.517,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42036_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42001/42001h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":28.5,   "lon":-84.517,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42035_1": {
            "file_names": ["42035/42035h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":29.232,   "lon":-94.413,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42035_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42035/42035h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":29.232,   "lon":-94.413,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42019_1": {
            "file_names": ["42019/42019h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":27.907,   "lon":-95.352,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42019_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42019/42019h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat":27.907,   "lon":-95.352,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42020_1": {
            "file_names": ["42020/42020h{0}.txt".format(x) for x in NDBC_A_years], #2005, 2006
            "file_type": "NBDC",
            "lat":26.968,   "lon":-96.694,
            "time_offset": 0, 
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"YYYY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WD",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42020_2": { #Note that there may be a change in vis distance for NDBC data between 2007 and 2015 from nmi to mi. This buoy doesn't measure vis, so it's not a concern here.
            "file_names": ["42020/42020h{0}.txt".format(x) for x in NDBC_B_years], # 2007 to present
            "file_type": "NBDC",
            "lat": 26.968, "lon": -96.694,
            "time_offset": 0,
            "UTM_offset":0,
            "time_single_column":False,
            "year_column":"#YY",
            "month_column":"MM",
            "day_column":"DD",
            "hour_column":"hh",
            "minute_column":"mm",
            "discard_2nd_line":True,
            "wave_column":"WVHT",
            "wave_unit":"m",
            "period_column":"DPD",
            "wind_column":"WSPD",
            "wind_unit":"m/s",
            "gust_column":"GST",
            "gust_unit":"m/s",
            "dir_column":"WDIR",
            "dir_unit":"degrees",
            "temp_column":"ATMP",
            "temp_unit":"C",
            "wtemp_column":"WTMP",
            "wtemp_unit":"C",
            "ignore_values":{'dir':'999', 'wind':'99.0', 'wave':'99.00', 'period':'99.00', 'gust':'99.0','temp':'999.0','wtemp':'999.0'}
        },
        "42035_9608": {
            "file_name": "Model_data/42035_9608.dat",
            "file_type": "csv",
            "lat":29.232,   "lon":-94.413,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42036_9092": {
            "file_name": "Model_data/42036_9092.dat",
            "file_type": "csv",
            "lat":28.5,   "lon":-84.517,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42039_9290": {
            "file_name": "Model_data/42039_9290.dat",
            "file_type": "csv",
            "lat":28.739,   "lon":-86.006,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42040_9642": {
            "file_name": "Model_data/42040_9642.dat",
            "file_type": "csv",
            "lat":29.203,   "lon":-88.203,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42002_6791": {
            "file_name": "Model_data/42002_6791.dat",
            "file_type": "csv",
            "lat":26.091,   "lon":-93.758,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42003_6732": {
            "file_name": "Model_data/42003_6732.dat",
            "file_type": "csv",
            "lat":26.007,   "lon":-85.648,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42019_8453": {
            "file_name": "Model_data/42019_8453.dat",
            "file_type": "csv",
            "lat":27.907,   "lon":-95.352,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42020_7624": {
            "file_name": "Model_data/42020_7624.dat",
            "file_type": "csv",
            "lat":26.968,   "lon":-96.694,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "42001_6574": {
            "file_name": "Model_data/42001_6574.dat",
            "file_type": "csv",
            "lat":25.897,   "lon":-89.668,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "Loc1_8787": {
            "file_name": "Model_data/Loc1_8787.txt",
            "file_type": "csv",
            "lat":28.25,    "lon":-95.5,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "Loc2_7519": {
            "file_name": "Model_data/Loc2_7519.txt",
            "file_type": "csv",
            "lat":26.875,   "lon":-94.75,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "Loc3_9042": {
            "file_name": "Model_data/Loc3_9042.txt",
            "file_type": "csv",
            "lat":28.5,     "lon":-90.75,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "Loc4_7800": {
            "file_name": "Model_data/Loc4_7800.txt",
            "file_type": "csv",
            "lat":27.125,   "lon":-89.625,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "Loc5_8544": {
            "file_name": "Model_data/Loc5_8544.txt",
            "file_type": "csv",
            "lat":27.875,   "lon":-84.0,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
        "Loc6_7712": {
            "file_name": "Model_data/Loc6_7712.txt",
            "file_type": "csv",
            "lat":27.0,     "lon":-85.75,
            "fill_undefined_waves":False,
            "time_column":{"Year":"YYYY","Month":"MM","Day":"DD","Hour":"HH","Minute":"null"},
            "time_single_column":False,
            "time_offset": 0,
            "UTM_offset":0,
            "wind_column":"Ws",
            "wind_unit":"m/s",
            "wave_column":"Hs",
            "wave_unit":"m",
            "vis_column":"Vis",
            "vis_unit":"m",
            "dir_column":"Wdir",
            "dir_unit":"degrees",
            "period_column":"Tm",
            "period_unit":"s",
            "ignore_values":{"wave":"-9.9","period":"-9.9"}
        },
    },


    "merges": {
        "42001": {
            "list_of_stations": ["42001_1","42001_2","42001_6574"],
            "merge_type":'single',
            "subsets":{"42001_6574":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42001_6574":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":25.897,   "lon":-89.668,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42040": {
            "list_of_stations": ["42040_1","42040_2",'42040_9642'],
            "merge_type":'single',
            "subsets":{"42040_9642":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42040_9642":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":29.203,   "lon":-88.203,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42039": {
            "list_of_stations": ["42039_1","42039_2",'42039_9290'],
            "merge_type":'single',
            "subsets":{"42039_9290":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42039_9290":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":28.739,   "lon":-86.006,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42003": {
            "list_of_stations": ["42003_1","42003_2",'42003_6732'],
            "merge_type":'single',
            "subsets":{"42003_6732":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42003_6732":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":26.007,   "lon":-85.648,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42002": {
            "list_of_stations": ["42002_1","42002_2",'42002_6791'],
            "merge_type":'single',
            "subsets":{"42002_6791":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42002_6791":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":26.091,   "lon":-93.758,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42036": {
            "list_of_stations": ["42036_1","42036_2",'42036_9092'],
            "merge_type":'single',
            "subsets":{"42036_9092":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42036_9092":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":28.5,   "lon":-84.517,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42035": {
            "list_of_stations": ["42035_1","42035_2",'42035_9608'],
            "merge_type":'single',
            "subsets":{"42035_9608":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42035_9608":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":29.232,   "lon":-94.413,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42019": {
            "list_of_stations": ["42019_1","42019_2",'42019_8453'],
            "merge_type":'single',
            "subsets":{"42019_8453":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42019_8453":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":27.907,   "lon":-95.352,
            "UTM_offset":0,
            "models": all_RGAs
        },
        "42020": {
            "list_of_stations": ["42020_1","42020_2",'42020_7624'],
            "merge_type":'single',
            "subsets":{"42020_7624":['wave','period','wind','vis']}, #Grabs only these columns from model data
            "nonstandard":{"42020_7624":{"wind":"wind2", 'wave':'wave2', 'period':'period2'}}, #Renames these columns - used for characterization, but not for RGAs
            "lat":26.968,   "lon":-96.694,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42035_9608':{
            "list_of_stations": ["42035_9608"],
            "merge_type":'single',
            "lat":29.232,   "lon":-94.413,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42036_9092':{
            "list_of_stations": ["42036_9092"],
            "merge_type":'single',
            "lat":28.5,   "lon":-84.517,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42039_9290':{
            "list_of_stations": ["42039_9290"],
            "merge_type":'single',
            "lat":28.739,   "lon":-86.006,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42040_9642':{
            "list_of_stations": ["42040_9642"],
            "merge_type":'single',
            "lat":29.203,   "lon":-88.203,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42002_6791':{
            "list_of_stations": ["42002_6791"],
            "merge_type":'single',
            "lat":26.091,   "lon":-93.758,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42003_6732':{
            "list_of_stations": ["42003_6732"],
            "merge_type":'single',
            "lat":26.007,   "lon":-85.648,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42019_8453':{
            "list_of_stations": ["42019_8453"],
            "merge_type":'single',
            "lat":27.907,   "lon":-95.352,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42020_7624':{
            "list_of_stations": ["42020_7624"],
            "merge_type":'single',
            "lat":26.968,   "lon":-96.694,
            "UTM_offset":0,
            "models": all_RGAs
        },
        '42001_6574':{
            "list_of_stations": ["42001_6574"],
            "merge_type":'single',
            "lat":25.897,   "lon":-89.668,
            "UTM_offset":0,
            "models": all_RGAs
        },
        'Loc1_8787':{
            "list_of_stations":['Loc1_8787'],
            "merge_type":'single',
            "lat":28.25,    "lon":-95.5,
            "UTM_offset":0,
            "models": all_RGAs
        },
        'Loc2_7519':{
            "list_of_stations":['Loc2_7519'],
            "merge_type":'single',
            "lat":26.875,   "lon":-94.75,
            "UTM_offset":0,
            "models": all_RGAs
        },
        'Loc3_9042':{
            "list_of_stations":['Loc3_9042'],
            "merge_type":'single',
            "lat":28.5,     "lon":-90.75,
            "UTM_offset":0,
            "models": all_RGAs
        },
        'Loc4_7800':{
            "list_of_stations":['Loc4_7800'],
            "merge_type":'single',
            "lat":27.125,   "lon":-89.625,
            "UTM_offset":0,
            "models": all_RGAs
        },
        'Loc5_8544':{
            "list_of_stations":['Loc5_8544'],
            "merge_type":'single',
            "lat":27.875,   "lon":-84.0,
            "UTM_offset":0,
            "models": all_RGAs
        },
        'Loc6_7712':{
            "list_of_stations":['Loc6_7712'],
            "merge_type":'single',
            "lat":27.0,     "lon":-85.75,
            "UTM_offset":0,
            "models": all_RGAs
        }
    },
    'comparisons':{
        'MEC1_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['MEC1']
        },
        'MEC2_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['MEC2']
        },
        'MEC3_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['MEC3']
        },
        'DISP1_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['DISP1']
        },
        'DISP2_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['DISP2']
        },
        'DISP3_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['DISP3']
        },
        'ISB1_comparison':{
            'merges':['42035_9608','42036_9092','42039_9290','42040_9642','42002_6791','42003_6732','42019_8453','42020_7624','42001_6574'],
            'models':['ISB1']
        }
    }
}
